---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgresql
spec:
  type: NodePort
  selector:
    app: postgresql
  ports:
  - nodePort: 30003
    port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgresql
spec:
  replicas: 1 ## Must set to 1 as there's no primary/secondary db.
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.1
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: db
          containerPort: 5432
          protocol: "TCP"
        envFrom:
        - configMapRef:
            name: postgresql-configmap
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: postgresql-pvc
