# https://tanka.dev/tutorial/refresher#writing-the-yaml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    name: prometheus
spec:
  type: NodePort
  selector:
    name: prometheus
  ports:
    - nodePort: 30002
      port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
        - image: quay.io/prometheus/prometheus:v2.40.4
          name: prometheus
          args:
            - "--storage.tsdb.retention.time=1h"
            - "--config.file=/etc/prometheus/cfg/prometheus.yaml"
            - "--storage.tsdb.path=/etc/prometheus/data/"
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: config-vol
              mountPath: /etc/prometheus/cfg
            - name: storage-vol
              mountPath: /etc/prometheus/data
      volumes:
        - name: config-vol
          configMap:
            defaultMode: 0644
            name: prometheus-configmap
        - name: storage-vol
          hostPath:
            path: /home/fuzhouch/projects/learning/minikube/prometheus/data
            type: DirectoryOrCreate
