apiVersion: v1
kind: Pod
metadata:
  name: simple-http-server
  labels:
    app: simple-http-server
spec:
  containers:
  - name: http-server
    image: python:3.8-alpine
    command: ["python", "-m", "http.server", "8000"]
    ports:
    - containerPort: 8000
    readinessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 20
