# minio-single defines a single-node minio service, deployable in
# minikube, and expose it via a NodePort for access from host.
# The storage used by minio service is hosted in local disk for study
# purpose.
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
kind: Service
apiVersion: v1
metadata:
  name: minio-svc
  namespace: minio
spec:
  type: NodePort
  selector:
    app: minio-single
  ports:
    - nodePort: 30001
      port: 5000
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio-single
  name: minio-single
  namespace: minio
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9000"
    prometheus.io/path: "/minio/v2/metrics/cluster"
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    env:
    - name: MINIO_ROOT_USER
      value: "minio"
    - name: MINIO_ROOT_PASSWORD
      value: "zaq1@WSX"
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: "public"
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :5000
    ports:
    - name: api
      containerPort: 9000
      protocol: "TCP"
    - name: console
      containerPort: 5000
      protocol: "TCP"
    volumeMounts:
    - mountPath: /data
      name: localvolume
  #nodeSelector:
    #kubernetes.io/hostname: kubealpha.local
  volumes:
  - name: localvolume
    hostPath:
      path: /home/fuzhouch/projects/learning/minikube/minio-single/data
      type: DirectoryOrCreate
