apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-configmap
  namespace: minio
  labels:
    app: minio
data:
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: "12345678"
  MINIO_PROMETHEUS_AUTH_TYPE: public
